{
	['src/*', 'src/web_ui/*'],
	[
		debug_info,
		{i, "../common/include"},
		{i, "../deps/nitrogen_core/include"},
		{i, "include"},
		{outdir, "ebin"},
		{d, 'TEST'},
		{nowarn_unused_function, {register_service, 2}},
		{nowarn_unused_function, {get_settings, 1}}
	]
}.
